/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 illustration.gltf --transform
Author: meatmaker (https://sketchfab.com/meatmaker)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/octopus-ca8db7533b5b4f58a70dc48e58fcbe9f
Title: Octopus
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/illustration-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['04___Default']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['05___Default']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['06___Default']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['18___Default']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['22___Default']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['23___Default']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Drawing001} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Drawing002} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Drawing003} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Drawing004} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Drawing005} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Drawing006} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Drawing007} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Drawing008} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['01___Default']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['07___Default']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['08___Default']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['08___Default']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['09___Default']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['10___Default']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['11___Default']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['12___Default']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.wire_000000000} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.wire_255255255} />
      </group>
    </group>
  )
}

useGLTF.preload('/illustration-transformed.glb')
